from __future__ import annotations

from itertools import pairwise
from typing import TYPE_CHECKING

import numpy as np
from numpy.typing import NDArray
from qiskit import transpile
from qiskit_aer.backends.aer_simulator import AerSimulator
from qiskit_aer.backends.aerbackend import AerBackend
from scipy import stats
from tqdm import tqdm

if TYPE_CHECKING:
    from quantum_circuit import ParametrizedQuantumCircuit
    from quantum_circuit.proxy_config import ProxyConfig


def make_dag(circ: ParametrizedQuantumCircuit) -> list[list[int]]:
    """
    Creates a directed acyclic graph for path counting through a quantum circuit.
    Returns an adjacency matrix where index 0 is a theoretical origin point connected
    to all qubits at the start, and index -1 is a theoretical end point where all
    qubits connect to at the end. Each index contains a list of what indices are next.
    Due to only one- and two-qubit gates existing these lists won't be long.
    """

    last_node_per_qubit = [i + 1 for i in range(circ.qubits)]
    adjacencies: list[list[int]] = [[x for x in last_node_per_qubit]]
    adjacencies.extend([[] for _ in range(circ.qubits)])
    next_vertex = circ.qubits + 1

    for layer in circ.gates:
        for gate in layer:
            if gate.type.is_single_qubit():
                continue
            # make the relevant qubits have edges to the two-qubit gate
            adjacencies[last_node_per_qubit[gate.qubits[0]]].append(next_vertex)
            adjacencies[last_node_per_qubit[gate.qubits[1]]].append(next_vertex)  # ty:ignore[index-out-of-bounds]

            # add the node for the two-qubit gate
            adjacencies.extend([[next_vertex + 1, next_vertex + 2], [], []])

            # make sure that the next two-qubit gate uses the new last nodes
            last_node_per_qubit[gate.qubits[0]] = next_vertex + 1
            last_node_per_qubit[gate.qubits[1]] = next_vertex + 2  # ty:ignore[index-out-of-bounds]

            # we added three nodes, so adding to the counter
            next_vertex += 3

    # make all the layers point to a final central vertex
    for last_node in last_node_per_qubit:
        adjacencies[last_node].append(next_vertex)
    adjacencies.append([])
    return adjacencies


def count_paths(graph: list[list[int]], origin: int, destination: int, memo: list[int | None]) -> int:
    """
    Using an adjacency matrix as generated by `make_dag` this function returns the
    number of ways to traverse the graph.
    The memo is used to improve the scaling of the algorithm and should start out as a list filled
    with `None` values of `len(graph)`
    """
    if origin == destination:
        return 1
    if (mo := memo[origin]) is not None:
        return mo

    adjacent = graph[origin]
    result = sum(count_paths(graph, adj, destination, memo) for adj in adjacent)
    memo[origin] = result
    return result


def paths_proxy(circs: list[ParametrizedQuantumCircuit]) -> np.ndarray[tuple[int], np.dtype[np.uint32]]:
    """
    Calculates the amount of paths to traverse each of the passed circuits,
    takes a list of circuits, and returns the count for each in the same order.
    """
    out: np.ndarray[tuple[int], np.dtype[np.uint32]] = np.zeros((len(circs)), dtype=np.dtype("uint32"))

    for i, circ in tqdm(enumerate(circs), total=len(circs), desc="Computing Paths", position=1, leave=False):
        dag = make_dag(circ)
        node_count = len(dag)
        out[i] = count_paths(dag, 0, node_count - 1, [None for _ in range(node_count)])

    return out
